name: Generate Snake Animation

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/snake.svg
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg
